version: '3.1'
services:
  stats-server:
    build: stats
    image: stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - ewm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-database
      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME-root}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD-root}

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-database
      - POSTGRES_USER=${DB_USER_NAME-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD-root}

  ewm-service:
    build: main
    image: main
    container_name: main
    ports:
      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-database
#      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME-root}
#      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD-root}
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm-db
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_DB=ewm-database
#      - POSTGRES_USER=${DB_USER_NAME-root}
#      - POSTGRES_PASSWORD=${DB_PASSWORD-root}
