DROP TABLE IF EXISTS endpoints, apps, stats CASCADE;

CREATE TABLE IF NOT EXISTS apps (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
app_name VARCHAR(100),
uri VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS endpoints (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
app_id BIGINT,
ip VARCHAR(100),
created TIMESTAMP,

CONSTRAINT fk_endpoints_to_apps FOREIGN KEY(app_id) REFERENCES apps(id)
);



